name: Agendar um Novo Evento!
description: Utilize essa opção caso deseje adicionar um novo evento!
title: "[Novo Evento] "
labels: event/new
body:
  - type: markdown
    attributes:
      value: |
        # Vamos agendar seu evento?

  - type: markdown
    attributes:
      value: |
        ## Informações Gerais do Evento

  - type: input
    id: event_name
    attributes:
      label: Nome do Evento
      description: Qual o nome do Evento?
      placeholder: "ex: TDC 2024"
    validations:
      required: true

  - type: input
    id: event_url
    attributes:
      label: Site do Evento
      description: Qual o Site/Link para mais informações do Evento?
      placeholder: "ex: https://www.tdc.com.br/"
    validations:
      required: true

  - type: dropdown
    id: event_type
    attributes:
      label: Modalidade do Evento
      description: "Qual será a modalidade do evento? Opções disponíveis: Presencial, Online e Híbrido"
      multiple: false
      options:
        - Presencial
        - Online
        - Híbrido
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Qual a Localidade do Evento?

  - type: input
    id: event_city
    attributes:
      label: "[Híbrido/Presencial] Cidade do Evento"
      description: Em qual cidade irá acontecer o evento? (Este campo é obrigatório para modalidades Híbrido e Presencial)
      placeholder: "Ex: São Paulo"
    validations:
      required: false

  - type: dropdown
    id: event_state
    attributes:
      label: "[Híbrido/Presencial] Estado Federativo do Evento"
      description: "Informe o estado federativo onde o evento ocorrerá. (Este campo é obrigatório para modalidades Híbrido e Presencial)"
      multiple: false
      default: 0
      options:
        - N/A
        - Acre (AC)
        - Alagoas (AL)
        - Amapá (AP)
        - Amazonas (AM)
        - Bahia (BA)
        - Ceará (CE)
        - Distrito Federal (DF)
        - Espírito Santo (ES)
        - Goiás (GO)
        - Maranhão (MA)
        - Mato Grosso (MT)
        - Mato Grosso do Sul (MS)
        - Minas Gerais (MG)
        - Pará (PA)
        - Paraíba (PB)
        - Paraná (PR)
        - Pernambuco (PE)
        - Piauí (PI)
        - Rio de Janeiro (RJ)
        - Rio Grande do Norte (RN)
        - Rio Grande do Sul (RS)
        - Rondônia (RO)
        - Roraima (RR)
        - Santa Catarina (SC)
        - São Paulo (SP)
        - Sergipe (SE)
        - Tocantins (TO)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Quando o evento vai acontecer?

  - type: dropdown
    id: event_year
    attributes:
      label: "Ano do Evento"
      description: "Qual o ano que irá acontecer o evento?"
      multiple: false
      default: 0
      options:
        - "2024"
        - "2025"

  - type: dropdown
    id: event_month
    attributes:
      label: "Mês do Evento"
      description: Em qual mês irá acontecer o evento?
      multiple: false
      options:
        - To Be Announced (TBA)
        - Janeiro (01)
        - Fevereiro (02)
        - Março (03)
        - Abril (04)
        - Maio (05)
        - Junho (06)
        - Julho (07)
        - Agosto (08)
        - Setembro (09)
        - Outubro (10)
        - Novembro (11)
        - Dezembro (12)
    validations:
      required: true

  - type: dropdown
    id: event_day
    attributes:
      label: "Dia do Evento"
      description: Selecione os dias em que o evento irá ocorrer. (Múltipla escolha)
      multiple: true
      options:
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
        - "27"
        - "28"
        - "29"
        - "30"
        - "31"
    validations:
      required: true
