name: "[CI] Markdown Lint"

on:
  push:
    branches: ["main", "feature/**"]
  workflow_dispatch:

run-name: "[CI] Markdown Lint - ${{ github.ref_name }}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail

      - uses: actions/upload-artifact@v4
        with:
          name: remark-lint-report
          path: public/

  custom-md-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Run custom markdown validation
        run: node src/validateReadme.js
