name: Adicionar Evento no README
on:
  issues:
    types: [opened]
jobs:
  update-readme:
    if: contains(github.event.issue.labels.*.name, 'event/new')
    runs-on: ubuntu-latest
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Obter detalhes do evento da issue
        id: event_details
        run: |
          event_name=$(echo "${{ github.event.issue.body }}" | grep 'Nome do Evento' | sed 's/^.*: //')
          event_url=$(echo "${{ github.event.issue.body }}" | grep 'Site do Evento' | sed 's/^.*: //')
          event_type=$(echo "${{ github.event.issue.body }}" | grep 'Modalidade do Evento' | sed 's/^.*: //')
          event_city=$(echo "${{ github.event.issue.body }}" | grep 'Cidade do Evento' | sed 's/^.*: //')
          event_state=$(echo "${{ github.event.issue.body }}" | grep 'Estado Federativo do Evento' | sed 's/^.*: //')
          event_month=$(echo "${{ github.event.issue.body }}" | grep 'Mês do Evento' | sed 's/^.*: //')
          event_day=$(echo "${{ github.event.issue.body }}" | grep 'Dia do Evento' | sed 's/^.*: //')

          echo "::set-output name=event_name::$event_name"
          echo "::set-output name=event_url::$event_url"
          echo "::set-output name=event_type::$event_type"
          echo "::set-output name=event_city::$event_city"
          echo "::set-output name=event_state::$event_state"
          echo "::set-output name=event_month::$event_month"
          echo "::set-output name=event_day::$event_day"

      - name: Atualizar README.md com novo evento
        run: |
          # Lógica para encontrar o mês correto no README.md
          month_section="<!-- ${{ steps.event_details.outputs.event_month }}:START -->"
          event_entry="- ${{ steps.event_details.outputs.event_day }}: [${{ steps.event_details.outputs.event_name }}](${{ steps.event_details.outputs.event_url }})"

          if [ "${{ steps.event_details.outputs.event_type }}" == "Presencial" ]; then
            event_entry="$event_entry - _${{ steps.event_details.outputs.event_city }}/${{ steps.event_details.outputs.event_state }}_ ![presencial]"
          elif [ "${{ steps.event_details.outputs.event_type }}" == "Híbrido" ]; then
            event_entry="$event_entry - _${{ steps.event_details.outputs.event_city }}/${{ steps.event_details.outputs.event_state }}_ ![híbrido]"
          else
            event_entry="$event_entry ![online]"
          fi

          # Atualiza o arquivo README.md
          sed -i "/$month_section/a\\$event_entry" README.md

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Criar uma nova branch
        run: |
          branch_name="feature/add-event-issue-${{ github.event.issue.number }}"
          git checkout -b $branch_name
          git add README.md
          git commit -m "Adicionando novo evento: ${{ steps.event_details.outputs.event_name }}"
          git push origin $branch_name

      - name: Criar Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: $branch_name
          title: "Adicionando novo evento: ${{ steps.event_details.outputs.event_name }}"
          body: |
            Este Pull Request adiciona o seguinte evento ao arquivo README.md:
