name: Processar Evento

on:
  issues:
    types: [opened]

jobs:
  process_event:
    runs-on: ubuntu-latest

    steps:
      - name: Obter detalhes do evento da issue
        id: event_details
        run: |

          event_info="${{ github.event.issue.body }}"

          get_event_values() {
            local event_info="$1"
            local key_name="$2"

            echo "$event_info" | awk '/^###/ { key=$0; next }NF { print key ": " $0 }' | grep "$key_name" | sed 's/^.*: //'
          }

          event_name=$(get_event_values "$event_info" 'Nome do Evento')
          event_url=$(get_event_values "$event_info" 'Site do Evento')
          event_type=$(get_event_values "$event_info" 'Modalidade do Evento')
          event_city=$(get_event_values "$event_info" 'Cidade do Evento')
          event_state=$(get_event_values "$event_info" 'Estado Federativo do Evento')
          event_year=$(get_event_values "$event_info" 'Ano do Evento')
          event_month=$(get_event_values "$event_info" 'Mês do Evento')
          event_day=$(get_event_values "$event_info" 'Dia do Evento')

          echo $event_name
          echo $event_url
          echo $event_type
          echo $event_city
          echo $event_state
          echo $event_year
          echo $event_month
          echo $event_day

          echo "event_name=$event_name" >> $GITHUB_OUTPUT
          echo "event_url=$event_url" >> $GITHUB_OUTPUT
          echo "event_type=$event_type" >> $GITHUB_OUTPUT
          echo "event_city=$event_city" >> $GITHUB_OUTPUT
          echo "event_state=$event_state" >> $GITHUB_OUTPUT
          echo "event_year=$event_year" >> $GITHUB_OUTPUT
          echo "event_month=$event_month" >> $GITHUB_OUTPUT
          echo "event_day=$event_day" >> $GITHUB_OUTPUT
