name: Processar Evento

on:
  issues:
    types: [opened]

jobs:
  process_event:
    runs-on: ubuntu-latest

    steps:
      - name: Obter detalhes do evento da issue
        id: event_details
        run: |
          event_name=$(echo "${{ github.event.issue.body }}" | grep 'Nome do Evento' | sed 's/^.*: //')
          event_url=$(echo "${{ github.event.issue.body }}" | grep 'Site do Evento' | sed 's/^.*: //')
          event_type=$(echo "${{ github.event.issue.body }}" | grep 'Modalidade do Evento' | sed 's/^.*: //')
          event_city=$(echo "${{ github.event.issue.body }}" | grep 'Cidade do Evento' | sed 's/^.*: //')
          event_state=$(echo "${{ github.event.issue.body }}" | grep 'Estado Federativo do Evento' | sed 's/^.*: //')
          event_month=$(echo "${{ github.event.issue.body }}" | grep 'Mês do Evento' | sed 's/^.*: //')
          event_day=$(echo "${{ github.event.issue.body }}" | grep 'Dia do Evento' | sed 's/^.*: //')

          echo $event_name
          echo $event_url
          echo $event_type
          echo $event_city
          echo $event_state
          echo $event_month
          echo $event_day

          echo "::set-output name=event_name::$event_name"
          echo "::set-output name=event_url::$event_url"
          echo "::set-output name=event_type::$event_type"
          echo "::set-output name=event_city::$event_city"
          echo "::set-output name=event_state::$event_state"
          echo "::set-output name=event_month::$event_month"
          echo "::set-output name=event_day::$event_day"
