name: Processar Evento

on:
  issues:
    types: [opened]

jobs:
  process_event:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'cadastrar/evento-presencial')
    steps:
      - name: Obter detalhes do evento da issue
        id: event_details
        run: |

          event_info="${{ github.event.issue.body }}"

          get_event_values() {
            local event_info="$1"
            local key_name="$2"

            echo "$event_info" | awk '/^###/ { key=$0; next }NF { print key ": " $0 }' | grep "$key_name" | sed 's/^.*: //'
          }

          event_name=$(get_event_values "$event_info" 'Nome do Evento')
          event_url=$(get_event_values "$event_info" 'Site do Evento')
          event_city=$(get_event_values "$event_info" 'Cidade do Evento')
          event_state=$(get_event_values "$event_info" 'Estado Federativo do Evento')
          event_year=$(get_event_values "$event_info" 'Ano do Evento')
          event_month=$(get_event_values "$event_info" 'Mês do Evento')
          event_day=$(get_event_values "$event_info" 'Dia do Evento')

          echo "event_name=$event_name" >> $GITHUB_OUTPUT
          echo "event_url=$event_url" >> $GITHUB_OUTPUT
          echo "event_city=$event_city" >> $GITHUB_OUTPUT
          echo "event_state=$event_state" >> $GITHUB_OUTPUT
          echo "event_year=$event_year" >> $GITHUB_OUTPUT
          echo "event_month=$event_month" >> $GITHUB_OUTPUT
          echo "event_day=$event_day" >> $GITHUB_OUTPUT

      - name: Criar evento com base nos valores inseridos
        run: |

          capitalize_first_letter() {
            echo "$1" | awk '{ for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); }1'
          }

          extract_abbreviation() {
              local input="$1"
              echo "$input" | sed -E 's/.*\(([^)]+)\).*/\1/'
          }

          day="${{ steps.event_details.outputs.event_day }}"
          name="${{ steps.event_details.outputs.event_name }}"
          url="${{ steps.event_details.outputs.event_url }}"
          city="${{ steps.event_details.outputs.event_city }}"
          state="${{ steps.event_details.outputs.event_state }}"
          type="Presencial"
          month=$(extract_abbreviation "${{ steps.event_details.outputs.event_month }}")

          if [[ $day == "_No response_" ]]; then
            month=TBA
          fi

          if [[ $month == "TBA" ]]; then
            string="- ${month}: [${name}](${url,,}) - _$(capitalize_first_letter "${city,,}")/$(extract_abbreviation "${state}")_ ![${type,,}]"
            echo $string
          else
            string="- ${day}: [${name}](${url,,}) - _$(capitalize_first_letter "${city,,}")/$(extract_abbreviation "${state}")_ ![${type,,}]"
            echo $string
          fi

          echo "string=$string" >> $GITHUB_OUTPUT

      - name: Modifica o README com bases nos valores informados
        env:
          README_PATH: "./README.md"
        run: |

          get_month_name() {
            local input="$1"
            echo "$input" | sed -E 's/ *\([^)]*\)//g; s/^[ ]*//; s/[ ]*$//' | tr '[:upper:]' '[:lower:]'
          }


          month=$(get_month_name "${{ steps.event_details.outputs.event_month }}")
          year="${{ steps.event_details.outputs.event_year }}"

          month_start="<!-- $(tr '[:lower:]' '[:upper:]' <<< "$month"):START -->"
          month_end="<!-- $(tr '[:lower:]' '[:upper:]' <<< "$month"):END -->"
          year_start="<!-- ANO${year}:START -->"
          year_end="<!-- ANO${year}:END -->"

          echo "$month"
          echo "$month_start"
          echo "$month_end"
          echo "$year_start"
          echo "$year_end"
